// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Create201912131516 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create201912131516));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130718027_Create201912131516"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
